import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Betelgeuse Arcade Emporium',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <div className="cursor"></div>
        <script dangerouslySetInnerHTML={{
          __html: `
            const cursor = document.querySelector('.cursor');

            document.addEventListener('mousemove', e => {
              cursor.setAttribute("style", "top: "+(e.pageY - 20)+"px; left: "+(e.pageX - 20)+"px;")
            });

            document.addEventListener('click', () => {
              cursor.classList.add("expand");

              setTimeout(() => {
                cursor.classList.remove("expand");
              }, 500)
            })
          `
        }} />
      </body>
    </html>
  );
}
